language: csharp
solution: SampleWebAPI.sln

install:
  - nuget restore SampleWebAPI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug SampleWebAPI.sln
  - msbuild /p:Configuration=Debug ./SampleWebAPITests/SampleWebAPITests.csproj 
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SampleWebAPITests/bin/Debug/SampleWebAPITests.dll
